pachicodes/deninho-bot

.gitignore
index.js
package.json

Iniciando o projeto

---

.gitignore
index.js
package-lock.json

#1 Criando função de Hello World do bot

Criando funçao de hello world

---

index.js

Add php lang to hello world

---

index.js

Esse comando espera duas pessoas darem o comando !duel e retorna um vecedor aleatoriamente

adicionando comando duel

---

index.js

Também adiciona suporte a variáveis de ambiente para fazer login com
usuáraios alternativos, bom pra testar.

Corrige duelo

---

index.js

?? precisa do node.js 14 para funfar, bora com o || que funciona em
versões mais antigas e é mais safe.

Corrige checagem de variável de ambiente

---

index.js

caso haja algum erro, so falar q vo tentar arrumar.

Adicionando o comando de ban

---

index.js

Corrige o !ban e também usa um nome que fica mais fácil de entender o
sentido.

Mudando variável para mensagem

---

index.js

funciona plmds

---

index.js

- client.say tem que ir pro target que é o canal
- botando um /me pra ficar coloridinho

Corrigindo ban

---

index.js

RINHA DE BAN

---

Dockerfile
README.md
docker-compose.yaml

Adicionando o Dockerfile e docker-compose.yaml para executar o DeninhoBot usando Docker.

Adicionando a possibilidade de executar o bot usando Docker

---

src/index.js

Adicionando mensagem no chat para avisar que o bot ficou online, pedido na issue #32 :grin:

adicionando mensagem no chat para avisar que o bot ficou online

---

README.md
src/commands/command-list.js
src/index.js

Add comando para listar opções de comandos disponíveis no bot

---

.env.example
.gitignore
README.md
package-lock.json
package.json
src/commands/caraio.js
src/commands/duel.js
src/index.js

> Requer que o PR #36 seja aprovado antes.
Corrige os problemas de lint no CI: https://github.com/pachicodes/deninho-bot/runs/1265668998?check_suite_focus=true#step:4:15

Corrigindo problemas de lint

---

src/commands/vitthin.js

Nesta Pull Request, adiciono o comando do vitthin
```
PACHIcodes: !vitthin
deninhobot: Piu Piu Piu
```

adicionando comando do vitthin

---

README.md
package-lock.json
package.json
src/commands/divulgador.js

Adicionando comandos de divulgaçao

---

src/commands/divulgador.js
src/commands/jpbrabo.js

closes #44 
<kbd>![image](https://user-images.githubusercontent.com/3982052/97693860-884fcf80-1a80-11eb-9cdd-619770d29c2a.png)</kbd>

Adicionando comandos !jp e !brabo

---

src/commands/duel.js

Refatorando o duel deninhobot

---

src/commands/duel.js

Duel contra o bot

---

.vscode/extensions.json

Incluindo arquivo com as extensões recomendadas para o desenvolvimento.
Quando o dev abrir o projeto no VScode, será exibido uma alerta no canto inferior direito perguntando se ele quer instalar as extensões. Caso não tenha e clique em "sim", será instalada as extensões: [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), [.editorconfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig), [.env](https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv) e [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).
Uma vez instaladas, quando as dependências do projeto também forem instaladas (eslint, prettier, etc), os arquivos serão corrigidos e "lintados" automaticamente quando salvos.

Extensões recomendadas para desenvolvimento
